In [10]:
import numpy as np

#1. Write a NumPy program to create an element-wise comparison (greater,
#greater_equal, less and less_equal) of two given arrays.

#Assuming arrays are of same shape.

a = np.array([3,4,5])
b = np.array([1,2,3])

print(f'"Equal to" as {np.equal(a,b)}.')
print(f'"Greater than" evaluates as {np.greater(a,b)}.')
print(f'"Greater than or equal to" evaluates as {np.greater_equal(a,b)}.')
print(f'"Less than" evaluates as {np.less(a,b)}.')
print(f'"Less than or equal to" evaluates as {np.less_equal(a,b)}.')

"Equal to" as [False False False].
"Greater than" evaluates as [ True  True  True].
"Greater than or equal to" evaluates as [ True  True  True].
"Less than" evaluates as [False False False].
"Less than or equal to" evaluates as [False False False].


In [58]:
#2. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

z = np.zeros((1,10))
o = np.ones((1,10))
f = np.full((1,10),5)
z, o, f

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]]))

In [22]:
#3. Write a NumPy program to generate a random number between 0 and 1
n = np.random.rand()
n

0.7110654196583878

In [31]:
#4. Write a NumPy program to create a 3x4 matrix filled with values from 10 to
21.

ttt = (np.random.rand(3,4)*10) + 10
ttt

array([[19.99107513, 17.92550063, 10.08104881, 10.00398931],
       [15.59623269, 11.13257794, 12.2906797 , 10.18109612],
       [17.1267485 , 13.36452646, 13.61076291, 13.32408349]])

In [40]:
#5. Write a NumPy program to convert an array to a float type.

orig = np.asfarray([1, 2, 3, 4])
orig.dtype

dtype('float64')

In [43]:
#6. Write a NumPy program to convert a list and tuple into arrays

lst = [1,2,3]
tup = (1,2,3)
flo = 3.3
dic = {1:2.0,2:4.0}

la = np.asarray(lst)
ta = np.asarray(tup)
fa = np.asarray(flo)
da = np.asarray(dic)
la, ta, fa, da

(array([1, 2, 3]),
 array([1, 2, 3]),
 array(3.3),
 array({1: 2.0, 2: 4.0}, dtype=object))

In [46]:
#7. Write a NumPy program to find common values between two arrays. 
array1 = np.array([ 0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

array = np.intersect1d(array1,array2)
array

array([10, 40])

In [63]:
#8. Write a NumPy program to find the indices of the maximum and minimum
#values along the given axis of an array. 

array = np.array([1, 2, 3, 4, 5, 6])
print(f'{array} has max {array.max()} with index {np.argmax(array)}.')
print(f'{array} has min {array.min()} with index {np.argmin(array)}.')

[1 2 3 4 5 6] has max 6 with index 5.
[1 2 3 4 5 6] has min 1 with index 0.


In [52]:
#9. Write a NumPy program to compute the determinant of a given square
#array.

sq = np.array([[1,2],[2,1]])
np.linalg.det(sq)

-2.9999999999999996

In [53]:
#10. Write a NumPy program to compute the multiplication of two given 
#matrixes.

a = np.array([[0,2],[3,4]])
b = np.array([[1,0],[0,1]])
a*b

array([[0, 0],
       [0, 4]])

In [57]:
#11. Write a NumPy program to create a structured array from given
#student name, height, class and their data types. Now sort the array on
#height. 

dtype = [('name','S10'),('class',int),('height',float)]
vals = [(b'James', 5, 48.5 ), 
         (b'Nail', 6, 52.5 ), 
         (b'Paul', 5, 42.1 ), 
         (b'Pit', 5, 40.11 )]
array = np.array(vals, dtype=dtype)
sarray = np.sort(array, order='height')
sarray

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S10'), ('class', '<i4'), ('height', '<f8')])

In [71]:
#12. Write a NumPy program to get the indices of the sorted elements of
#a given array. 
array = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

sarray = np.argsort(array)
sarray

array([0, 3, 4, 6, 1, 5, 2], dtype=int64)

In [66]:
#13. Write a NumPy program to concatenate element-wise two arrays of
#string. 
array1 = np.array(['Python', 'PHP'])
array2 = np.array(['Java', 'C++'])

carray = np.concatenate((array1,array2))
carray

array(['Python', 'PHP', 'Java', 'C++'], dtype='<U6')

In [68]:
#14. Write a NumPy program to repeat all the elements three times of a
#given array of string 
#Expected Output:
array = np.array(['Python', 'PHP', 'Java', 'C++'])

arrr = np.repeat(array,3)
arrr

array(['Python', 'Python', 'Python', 'PHP', 'PHP', 'PHP', 'Java', 'Java',
       'Java', 'C++', 'C++', 'C++'], dtype='<U6')

In [69]:
#15. Write a NumPy program to split the element of a given array with
#spaces. 
array = np.array(['Python', 'PHP', 'Java', 'C++'])

spaced = np.char.split(array)
spaced

array([list(['Python']), list(['PHP']), list(['Java']), list(['C++'])],
      dtype=object)